package com.example.domain.api.models


import com.squareup.moshi.Json


data class SchoolDtoItem(
    val dbn: String,
    @field:Json(name = "school_name") var schoolName: String?,
    val boro: String,
    @Json(name = "overview_paragraph") val overviewParagraph: String,
    @Json(name = "school_10th_seats") val school10thSeats: String,
    @Json(name = "academicopportunities1") val academicOpportunities1: String,
    @Json(name = "academicopportunities2") val academicOpportunities2: String,
    @Json(name = "ell_programs") val ellPrograms: String,
    val neighborhood: String,
    @Json(name = "building_code") val buildingCode: String,
    val location: String,
    @Json(name = "phone_number") val phoneNumber: String,
    @Json(name = "fax_number") val faxNumber: String,
    @Json(name = "school_email") val schoolEmail: String,
    val website: String,
    val subway: String,
    val bus: String,
    @Json(name = "grades2018") val grades2018: String,
    @Json(name = "finalgrades") val finalGrades: String,
    @Json(name = "total_students") val totalStudents: String,
    @Json(name = "extracurricular_activities") val extracurricularActivities: String,
    @Json(name = "school_sports") val schoolSports: String,
    @Json(name = "attendance_rate") val attendanceRate: String,
    @Json(name = "pct_stu_enough_variety") val pctStuEnoughVariety: String,
    @Json(name = "pct_stu_safe") val pctStuSafe: String,
    @Json(name = "school_accessibility_description") val schoolAccessibilityDescription: String,
    @Json(name = "directions1") val directions1: String,
    @Json(name = "requirement1_1") val requirement11: String,
    @Json(name = "requirement2_1") val requirement21: String,
    @Json(name = "requirement3_1") val requirement31: String,
    @Json(name = "requirement4_1") val requirement41: String,
    @Json(name = "requirement5_1") val requirement51: String,
    @Json(name = "offer_rate1") val offerRate1: String,
    val program1: String,
    val code1: String,
    val interest1: String,
    val method1: String,
    @Json(name = "seats9ge1") val seats9ge1: String,
    @Json(name = "grade9gefilledflag1") val grade9gefilledflag1: String,
    @Json(name = "grade9geapplicants1") val grade9geapplicants1: String,
    @Json(name = "seats9swd1") val seats9swd1: String,
    @Json(name = "grade9swdfilledflag1") val grade9swdfilledflag1: String,
    @Json(name = "grade9swdapplicants1") val grade9swdapplicants1: String,
    @Json(name = "seats101") val seats101: String,
    @Json(name = "admissionspriority11") val admissionspriority11: String,
    @Json(name = "admissionspriority21") val admissionspriority21: String,
    @Json(name = "admissionspriority31") val admissionspriority31: String,
    @Json(name = "grade9geapplicantsperseat1") val grade9geapplicantsperseat1: String,
    @Json(name = "grade9swdapplicantsperseat1") val grade9swdapplicantsperseat1: String,
    @Json(name = "primary_address_line_1") val primaryAddressLine1: String,
    val city: String,
    val zip: String,
    @Json(name = "state_code") val stateCode: String,
    val latitude: String,
    val longitude: String,
    @Json(name = "community_board") val communityBoard: String,
    @Json(name = "council_district") val councilDistrict: String,
    @Json(name = "census_tract") val censusTract: String,
    val bin: String,
    val bbl: String,
    val nta: String,
    val borough: String
)